### PR TITLE
Fix panic when decoding

### LINKED ISSUE #298: panic: cannot consume from pending buffer
In https://github.com/rust-lang/crates.io/pull/9622 we upgraded crates.io to the latest `async-compression` release (v0.4.14), which appears to be causing issues on our staging environment:

https://rust-lang.sentry.io/share/issue/9e273e28600f48a5aec2ad9e127afbbf/

The code inside the `object_store` crate is throwing a "cannot consume from pending buffer" panic, but the root cause seems to be originating from the `async-compression` crate. We use both crates roughly like this:

```rust
let reader = object_store::buffered::BufReader::new(store, &meta);
let decompressor = Decompressor::from_extension(reader, path.extension())?;
```

I assume that https://github.com/Nullus157/async-compression/pull/294 is causing this issue, but I don't know the code well enough to find the exact bug in the code changes that are causing this behavior.

### PR DESCRIPTION
**Pull request by NobodyXu**
Fix #298

### CODE REVIEW

**Comment by NobodyXu** [comment]
cc @Turbo87 Can you try this PR please?
It should fix the error you've encountered.

**Comment by Turbo87** [comment]
just pushed it to our staging environment. it'll take a while to verify that it's actually fixed, but thanks for the very quick response! ❤️

**Review by robjtede — APPROVED** [review]

**Comment by robjtede** [comment]
lgtm but we can wait for til EoD to release in case @Turbo87 reports any issues

**Comment by Turbo87** [comment]
I pushed https://github.com/Turbo87/crates.io/commit/e6431c9d983044cb4e6c78435a41d25d5a3bf627 to our staging environment, but Sentry shows:

Bildschirmfoto 2024-10-12 um 11 17 22

which seems to indicate that the issue still exists or I've messed up the update 😅

**Comment by NobodyXu** [comment]
Hmmm the branch is auto deleted since it is merged to main.

Maybe you need to use the main branch, or the latest commit hash?

**Comment by Turbo87** [comment]
yeah, though when I did the commit the branch was not merged yet and the lockfile includes the commit hash. since you're using proper, non-squash merges here the commit hash should still be resolvable by cargo.

but just in case I'll update it to `main` and try again 👍

**Comment by NobodyXu** [comment]
> the lockfile includes the commit hash.

Well hmmm I don't know

**Comment by Turbo87** [comment]
I changed it over to https://github.com/Turbo87/crates.io/commit/c58174f77d00bad1372c66cc03efd68dfb57ecfd, but according to Sentry it's still happening with this deployment too :-/

**Comment by NobodyXu** [comment]
Thanks, is there any unwinding/panic info?

**Comment by Turbo87** [comment]
Bildschirmfoto 2024-10-12 um 12 16 02

basically all I can see is the stacktrace and a bit of metadata, but nothing else related to the panic.

I just deployed https://github.com/rust-lang/crates.io/pull/9639 to the staging environment to double check and that did indeed "fix" the issue for now.

**Pull request merged**
