### PR TITLE
flush data still available in the decoder when no input

### LINKED ISSUE #123: Decoder might block if there is data remaining to be flushed from the codec and the stream blocks
See https://github.com/gyscos/zstd-rs/issues/119, I'm pretty sure the local `bufread::Decoder` implementations suffer from this same issue. My first attempt at writing a test case failed to fail though.

### PR DESCRIPTION
**Pull request by nl5887**
closes #123

### CODE REVIEW

**Comment by michalfita** [comment]
@nl5887 any chance this could be pushed up the priorites list, please?
Thanks in advance.

**Comment by Nemo157** [comment]
I would really like a testcase with this to make sure it does fix the issue and there won't be a regression. I'll probably take another try at writing one myself, but I remember failing at it once already.

**Review by NobodyXu — CHANGES_REQUESTED** [review]
Can you please rebase this PR against main?

**Comment by michalfita** [comment]
@nl5887 isn't recently very active on GH, hopefully he gets this ping.

**Comment by robjtede** [comment]
Since this PR has not allowed maintainer edits, I've rebased and opened #247.

**Comment by NobodyXu** [comment]
Thanks, I've close this

**Pull request closed without merging**
