### PR TITLE
Update to zstd 0.12 / zstd-safe 6

### PR DESCRIPTION
**Pull request by maxburke**

### CODE REVIEW

**Comment by gaby** [comment]
@Nemo157 there's a bug in zstd that was fixed on the latest release v1.5.5, can we get this PR merged?

**Comment by NobodyXu** [comment]
This PR needs a rebase against main.

**Comment by maxburke** [comment]
done

**Comment by NobodyXu** [comment]
Thank you!

**Comment by robjtede** [comment]
mentioned upgrade in e66f3a139d2f1d32ff4a5af1489e679e2fac6704 since it's potentially pertinent for native build reasons

**Pull request merged**
