### PR TITLE
Fix a minimum-versions issue

### PR DESCRIPTION
**Pull request by g2p**
Tested with:

    cargo +nightly update -Zminimal-versions; cargo check --all-features

See https://github.com/rust-lang/flate2-rs/pull/221
(And #85 would be nice)

### CODE REVIEW

**Review by NobodyXu — CHANGES_REQUESTED** [review]
Can you add a new job to CI which tests the minimal versions?

**Comment by g2p** [comment]
> Can you add a new job to CI which tests the minimal versions?

Added!

**Review by NobodyXu — APPROVED** [review]

**Comment by NobodyXu** [comment]
Thank you @g2p

**Comment by robjtede** [comment]
It's nice that the tools to catch this sort of stuff are getting easier to use!

**Pull request merged**
