### PR TITLE
Upgrade to Brotli v5

### PR DESCRIPTION
**Pull request by nyurik**

### CODE REVIEW

**Review by NobodyXu — APPROVED** [review]
Thank you, LGTM, I would ask @robjtede to do a double-check

**Comment by NobodyXu** [comment]
Seems that @robjtede is busy.

I will probably merge this afternoon, after double-checking it, and cut a new release.

**Comment by robjtede** [comment]
sorry yea this dropped off my notifications, looks fine to me

**Comment by NobodyXu** [comment]
Thanks, would cut a new release soon

**Comment by NobodyXu** [comment]
async-compression 0.4.9 has been published

**Pull request merged**
